create table if not exists public.courses (
  course_code text primary key,
  name text not null,
  lecture_url text,
  tutorial_url text,
  meet_url text
);

create table if not exists public.class_sessions (
  id uuid primary key default gen_random_uuid(),
  day_of_week smallint not null check (day_of_week between 0 and 6),
  start_hour numeric(4, 2) not null check (start_hour between 0 and 24),
  end_hour numeric(4, 2) not null check (end_hour between 0 and 24),
  course_code text not null references public.courses(course_code) on update cascade on delete cascade,
  group_code text not null,
  session_type text not null check (session_type in ('Lecture', 'Tutorial')),
  mode text not null,
  check (end_hour > start_hour),
  unique (day_of_week, start_hour, course_code, group_code, session_type)
);

create table if not exists public.quick_links (
  id text primary key,
  name text not null,
  description text not null,
  url text not null,
  category text not null check (category in ('campus', 'tools')),
  icon text not null check (icon in ('book', 'calendar', 'campus', 'file', 'message', 'sparkles', 'video', 'wifi')),
  campus_only boolean not null default false,
  sort_order integer not null unique
);

create table if not exists public.bus_routes (
  direction text primary key check (direction in ('toKampus', 'toKemumin')),
  from_location text not null,
  to_location text not null,
  short_label text not null
);

create table if not exists public.bus_operating_days (
  day_of_week smallint primary key check (day_of_week between 0 and 6)
);

create table if not exists public.bus_departures (
  id bigint generated by default as identity primary key,
  direction text not null references public.bus_routes(direction) on update cascade on delete cascade,
  departure_time time not null,
  sort_order integer not null,
  unique (direction, sort_order),
  unique (direction, departure_time)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  matric_no text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.custom_events (
  id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  location text not null default 'No location',
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  all_day boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (user_id, id),
  check (ends_at > starts_at)
);

create table if not exists public.planner_items (
  id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null check (kind in ('assignment', 'exam', 'revision')),
  title text not null,
  course_code text not null,
  due_at timestamptz not null,
  notes text not null default '',
  hyperlink text,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (user_id, id)
);

create index if not exists custom_events_user_starts_idx on public.custom_events(user_id, starts_at);
create index if not exists planner_items_user_due_idx on public.planner_items(user_id, due_at);

alter table public.courses enable row level security;
alter table public.class_sessions enable row level security;
alter table public.quick_links enable row level security;
alter table public.bus_routes enable row level security;
alter table public.bus_operating_days enable row level security;
alter table public.bus_departures enable row level security;
alter table public.profiles enable row level security;
alter table public.custom_events enable row level security;
alter table public.planner_items enable row level security;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'courses', 'class_sessions', 'quick_links', 'bus_routes',
    'bus_operating_days', 'bus_departures'
  ] loop
    execute format('drop policy if exists %I on public.%I', 'Public can read ' || table_name, table_name);
    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true)',
      'Public can read ' || table_name,
      table_name, table_name
    );
  end loop;
end
$$;

drop policy if exists "Users can read their profile" on public.profiles;
create policy "Users can read their profile" on public.profiles for select to authenticated using (auth.uid() = id);
drop policy if exists "Users can create their profile" on public.profiles;
create policy "Users can create their profile" on public.profiles for insert to authenticated with check (auth.uid() = id);
drop policy if exists "Users can update their profile" on public.profiles;
create policy "Users can update their profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Users can manage their custom events" on public.custom_events;
create policy "Users can manage their custom events" on public.custom_events for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users can manage their planner items" on public.planner_items;
create policy "Users can manage their planner items" on public.planner_items for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant select on public.courses, public.class_sessions, public.quick_links,
  public.bus_routes, public.bus_operating_days, public.bus_departures to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.custom_events, public.planner_items to authenticated;

insert into public.courses (course_code, name, lecture_url, tutorial_url, meet_url) values
  ('ATF10203', 'ASAS KEUSAHAWANAN', 'https://ecampus.umk.edu.my/course/view.php?id=111126122', 'https://ecampus.umk.edu.my/course/view.php?id=111126123', 'https://meet.google.com/cxf-dvjn-wtt'),
  ('HFT10103', 'ASAS PENGURUSAN', 'https://ecampus.umk.edu.my/course/view.php?id=111127150', 'https://ecampus.umk.edu.my/course/view.php?id=111127151', null),
  ('HFT10403', 'PRINSIP EKONOMI', 'https://ecampus.umk.edu.my/course/view.php?id=111127162', 'https://ecampus.umk.edu.my/course/view.php?id=111127163', null),
  ('HTP10103', 'PENGENALAN KEPADA INDUSTRI KEUSAHAWANAN PELANCONGAN', 'https://ecampus.umk.edu.my/course/view.php?id=111127392', 'https://ecampus.umk.edu.my/course/view.php?id=111127393', null),
  ('UBI2022', 'BAHASA INGGERIS DALAM KOMUNIKASI PERNIAGAAN', 'https://ecampus.umk.edu.my/course/view.php?id=111128263', null, null),
  ('UKS10401', 'BADMINTON', 'https://ecampus.umk.edu.my/course/view.php?id=111128565', null, null),
  ('USK10602', 'FALSAFAH DAN CABARAN SEMASA', 'https://ecampus.umk.edu.my/course/view.php?id=111128828', null, 'https://meet.google.com/gkf-qori-fjy')
on conflict (course_code) do nothing;

insert into public.class_sessions (day_of_week, start_hour, end_hour, course_code, group_code, session_type, mode) values
  (0, 8, 10, 'UBI2022', 'PC20', 'Lecture', 'Online 10K'),
  (0, 10, 11, 'HTP10103', 'L1T1', 'Tutorial', 'Online 1K'),
  (0, 11, 13, 'HFT10103', 'L1', 'Lecture', 'K202D'),
  (0, 16, 18, 'ATF10203', 'H1', 'Lecture', 'Online 8K'),
  (0, 20, 21, 'HFT10103', 'L1T1', 'Tutorial', 'Async_1'),
  (1, 14, 16, 'USK10602', 'PC15', 'Lecture', 'Online 5K'),
  (2, 17, 19, 'UKS10401', 'LK1', 'Lecture', 'K204D'),
  (3, 8, 10, 'HTP10103', 'L1', 'Lecture', 'K204D'),
  (3, 10, 11, 'HFT10403', 'L1T1', 'Tutorial', 'Online 1K'),
  (4, 8, 10, 'HFT10403', 'L1', 'Lecture', 'K202D')
on conflict (day_of_week, start_hour, course_code, group_code, session_type) do nothing;

insert into public.quick_links (id, name, description, url, category, icon, campus_only, sort_order) values
  ('e-capsule', 'E-Capsule', 'Student services portal', 'https://capsule.umk.edu.my/', 'campus', 'campus', false, 1),
  ('e-campus', 'E-Campus', 'Courses and learning materials', 'https://ecampus.umk.edu.my/my/', 'campus', 'book', false, 2),
  ('blok-kemumin-wifi', 'Blok Kemumin WiFi', 'Campus network access', 'http://10.255.255.1:8080/index.html', 'campus', 'wifi', true, 3),
  ('kampus-kota-system', 'Kampus Kota System', 'Kota campus network portal', 'http://1.1.1.2/', 'campus', 'wifi', true, 4),
  ('umk-official', 'UMK Official', 'University news and information', 'https://www.umk.edu.my/en/', 'campus', 'campus', false, 5),
  ('umk-library', 'UMK Library', 'Library services and catalogue', 'https://library.umk.edu.my/en/index.cfm', 'campus', 'book', false, 6),
  ('e-pams', 'E-PAMS', 'Past year examination papers', 'https://exampaper.umk.edu.my/', 'campus', 'file', false, 7),
  ('google-meet', 'Google Meet', 'Join or start a meeting', 'https://meet.google.com/', 'tools', 'video', false, 8),
  ('google-calendar', 'Google Calendar', 'Open the full calendar', 'https://calendar.google.com/', 'tools', 'calendar', false, 9),
  ('claude', 'Claude', 'AI workspace', 'https://claude.ai/', 'tools', 'sparkles', false, 10),
  ('notebooklm', 'NotebookLM', 'Research and source notebook', 'https://notebooklm.google.com/', 'tools', 'sparkles', false, 11),
  ('whatsapp-web', 'WhatsApp Web', 'Messages in your browser', 'https://web.whatsapp.com/', 'tools', 'message', false, 12),
  ('google-drive', 'Google Drive', 'Cloud storage and file sharing', 'https://drive.google.com/', 'tools', 'file', false, 13)
on conflict (id) do nothing;

insert into public.bus_routes (direction, from_location, to_location, short_label) values
  ('toKampus', 'Kemumin', 'Kampus Kota', 'TO KAMPUS'),
  ('toKemumin', 'Kampus Kota', 'Kemumin', 'TO KEMUMIN')
on conflict (direction) do nothing;

insert into public.bus_operating_days (day_of_week) values (0), (1), (2), (3), (4)
on conflict (day_of_week) do nothing;

insert into public.bus_departures (direction, departure_time, sort_order) values
  ('toKampus', '07:20', 1), ('toKampus', '07:40', 2), ('toKampus', '08:20', 3), ('toKampus', '09:00', 4),
  ('toKampus', '10:20', 5), ('toKampus', '11:10', 6), ('toKampus', '12:00', 7), ('toKampus', '12:40', 8),
  ('toKampus', '13:30', 9), ('toKampus', '15:20', 10), ('toKampus', '16:00', 11), ('toKampus', '17:20', 12),
  ('toKampus', '18:00', 13), ('toKampus', '18:40', 14), ('toKampus', '20:00', 15), ('toKampus', '22:40', 16),
  ('toKemumin', '08:00', 1), ('toKemumin', '08:40', 2), ('toKemumin', '09:40', 3), ('toKemumin', '11:00', 4),
  ('toKemumin', '11:40', 5), ('toKemumin', '12:20', 6), ('toKemumin', '13:00', 7), ('toKemumin', '14:00', 8),
  ('toKemumin', '15:40', 9), ('toKemumin', '17:00', 10), ('toKemumin', '17:40', 11), ('toKemumin', '18:20', 12),
  ('toKemumin', '19:00', 13), ('toKemumin', '22:20', 14), ('toKemumin', '23:00', 15)
on conflict (direction, departure_time) do nothing;
